version: '3.4'

services:

  consul:
    image: consul:1.6.3
    command: agent -server -ui -node=server1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
    - "8500:8500"
    networks:
      - app

  entry:
    image: com.example/entry
    ports:
    - "8080-8081:8080"
    networks:
      - app
    depends_on:
      - consul

  task:
    image: com.example/task
    ports:
      - "8600-8601:8600"
    networks:
      - app
    depends_on:
      - consul

networks:
  app:
    driver: bridge