version: '3.4'

services:

  consul:
    image: consul:1.6.3
    ports:
    - "8501:8500"
    - "8600:8600/udp"
    networks:
      - app

  entry:
    image: com.example/entry
    ports:
    - "8080:8080"
    networks:
      - app
    environment:
      - CONSUL_HOST=consul:consul
    depends_on:
      - consul


networks:
  app:
    driver: bridge