spring:
  application:
    name: task
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 5s
        enabled: true
        deregister: true
        service-name: ${spring.application.name}
logging:
  level:
    root: warn

server:
  port: 8601